on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
      - name: Every time - Date
        run: date
