# on:
#   schedule:
#     - cron: '* */10 * * *'

on: [push]

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    container: rockylinux
    steps:
      - name: Every time
        run: echo "This step will always run"
        
      - name: List Dir
        run: pwd

      - name: Bash Script
        env:
          MY_ENV_VAR: ${{ secrets.MY_VAR }}
        run: bash ./script.sh
